<?php
/**
 * Created by PhpStorm.
 * User: Lin
 * Date: 2019/2/14
 * Time: 10:11
 * 后台用户登录
 */

namespace app\admin\controller;

use app\admin\model\Admin;
use think\Controller;
use think\Request;


class Login extends Controller
{
   public function _initialize()
   {
       parent::_initialize(); // TODO: Change the autogenerated stub
       $check_login=session("check_login");
       if(!empty($check_login)){
//           $this->redirect("index/index");
       }
   }
   /**
    * 注册页面
    * lin
   */
   public function login(){
       return view("public/login");
   }
   /**
    * 登录提交
    * lin
   */
   public function sendlogin(){
       //请求信息
       $request = Request::instance();
       //判断是否是post提交
       if(!$request->isPost()){
           $this->error("请求错误");
       }
       $post=$request->post();//post参数
       $account=$post["account"];//登录账号
       $password=md5($post["password"]);//登录密码
       //判断账号密码是否为空
       if(empty($password)||empty($account)){
           $this->error("账号密码不得为空");
       }
       $admin=new Admin();
       $info=$admin->login($account,$password);
       //判断用户是否存在
       if(!$info["status"]){
           $this->error($info["msg"]);
       }else{
           session("check_login",true);//保存登录状态
           session("admin_id",$info["id"]);
           $this->success($info["msg"]);
       }
   }

    /**
     * 注销登录
     * lin
     */
   public function loginout(){
       session_destroy();//清除session
       $this->success("退出成功！");
   }
}